
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafid
 */
public class MainFrame extends javax.swing.JFrame {
     String nol_jam="",nol_menit="",nol_detik="";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        selectData();
        setJam();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelJam = new javax.swing.JLabel();
        LabelTanggal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id_barang = new javax.swing.JTextField();
        harga_barang = new javax.swing.JTextField();
        jumlah_barang = new javax.swing.JTextField();
        Tanggalan = new com.toedter.calendar.JDateChooser();
        nama_kasir = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 30));

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 30));

        jLabel4.setText("Jumlah Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 30));

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, 30));

        jLabel6.setText("Nama Kasir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        diskon.setEditable(false);
        diskon.setBackground(new java.awt.Color(255, 255, 255));
        diskon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonActionPerformed(evt);
            }
        });
        getContentPane().add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 170, 30));

        jLabel2.setText("Harga Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, 30));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelJam.setText("Waktu");
        jPanel1.add(LabelJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 150, 20));

        LabelTanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelTanggal.setText("Tanggal");
        jPanel1.add(LabelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 120, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rafid\\Downloads\\Image\\ts.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Koperasi Siswa SMK Telkom Malang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Attitude Is Everything");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 90));

        id_barang.setEditable(false);
        id_barang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(id_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, 30));

        harga_barang.setEditable(false);
        harga_barang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(harga_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, 30));
        getContentPane().add(jumlah_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, 30));
        getContentPane().add(Tanggalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 170, 30));
        getContentPane().add(nama_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, 30));

        nama_barang.setEditable(false);
        nama_barang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, 30));

        jLabel7.setText("Id Barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 300, 10);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Transaksi Barang");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 0, 119, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 360));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 30));

        jButton1.setText("Cek Diskon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 110, 30));

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 90, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 580, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id_barang", "Nama_Barang", "Harga_Barang"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(50, 40, 470, 240);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Daftar Harga Barang");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 0, 580, 40);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 580, 290));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        tblData2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama_Kasir", "Nama_Barang", "Harga_Satuan", "Jumlah_Barang", "Total_Harga", "Diskon", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tblData2);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 850, 120);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 890, 150));

        setSize(new java.awt.Dimension(926, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1){
        id_barang.setText(tblData.getValueAt(baris, 0).toString());
        nama_barang.setText((String) tblData.getValueAt(baris, 1));
        harga_barang.setText((String) tblData.getValueAt(baris, 2));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggalan.getDate());
        String JK = "";
        
        int harga = Integer.parseInt(harga_barang.getText());
        int jumlah = Integer.parseInt(jumlah_barang.getText());
        int total = harga*jumlah;
        
        if("".equals(nama_kasir.getText())||"".equals(id_barang.getText())||"".equals(nama_barang.getText())||"".equals(harga_barang.getText())||"".equals(jumlah_barang.getText())||"".equals(diskon.getText())||Tanggalan.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", 
            JOptionPane.WARNING_MESSAGE);
        }else{
            
                
        
        String SQL = "insert into  tb_transaksi (Nama_Kasir,Nama_Barang,Harga_Satuan,Jumlah_Barang,Total_Harga,Diskon,Tanggal) "
                + "VALUES('"+nama_kasir.getText()+"', '"+nama_barang.getText()+"', '"+harga_barang.getText()+"', '"+jumlah_barang.getText()+"', '"+total+"',"
                + "'"+diskon.getText()+"','"+tanggal+"')";
        int status = KoneksiDB.execute(SQL);
        if(status == 1){
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        diskon();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             selectData2();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        nama_kasir.setText("");
        id_barang.setText("");
        nama_barang.setText("");
        harga_barang.setText("");
        jumlah_barang.setText("");
        diskon.setText("");
        Tanggalan.setDate(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MessageFormat header = new MessageFormat("Daftar Transaksi");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        
        try {
            tblData2.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    private void selectData(){
    String kolom[] = {"Id_Barang","Nama_Barang","Harga_Barang"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM tb_barang";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String Id = rs.getString(1);
               String NmBrg = rs.getString(2);
               String HrgBrg = rs.getString(3);
               String data [] = {Id,NmBrg,HrgBrg};
               dtm.addRow(data);
           }   
        }catch(SQLException ex){
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       tblData.setModel(dtm);
    }
    private void selectData2(){
    String kolom[] = {"Nomor","Nama_Kasir","Nama_Barang","Harga_Satuan","Jumlah_Barang","Total_Harga","Diskon","Tanggal"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM tb_transaksi";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String nmr = rs.getString(1);
               String nmksr = rs.getString(2);
               String nmbrg = rs.getString(3);
               String hrgstn = rs.getString(4);
               String jmlhbrg = rs.getString(5);
               String ttl = rs.getString(6);
               String dskn = rs.getString(7);
               String tgl = rs.getString(8);
               
               String data [] = {nmr,nmksr,nmbrg,hrgstn,jmlhbrg,ttl,dskn,tgl};
               dtm.addRow(data);
           }   
        }catch(SQLException ex){
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       tblData2.setModel(dtm);
    }
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyy");
        LabelTanggal.setText(kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                LabelJam.setText("Jam "+jam + ":" + menit + ":" + detik );
            }
        };
        new Timer(100, taskPerformer).start();
    }
    public void diskon()
    {
        int harga = Integer.parseInt(harga_barang.getText());
        int jumlah = Integer.parseInt(jumlah_barang.getText());
        int total = harga*jumlah;
        
        if(total > 100000)
        {
            diskon.setText("10%");
        }
        else{
            diskon.setText("0%");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJam;
    private javax.swing.JLabel LabelTanggal;
    private com.toedter.calendar.JDateChooser Tanggalan;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField harga_barang;
    private javax.swing.JTextField id_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jumlah_barang;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_kasir;
    private javax.swing.JTable tblData;
    private javax.swing.JTable tblData2;
    // End of variables declaration//GEN-END:variables
}
